<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
register_field_group(array (
	'id' => 'acf_qa',
	'title' => 'Q&A',
	'fields' => array (
                array (
			'key' => 'field_qa_author_name',
			'label' => '執筆者',
			'name' => 'author',
			'type' => 'text',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => '',
			'instructions' => '',
		),
                array (
			'key' => 'field_qa_author_company',
			'label' => '執筆者社名',
			'name' => 'company',
			'type' => 'text',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'formatting' => 'html',
			'instructions' => '',
		),
                array (
			'key' => 'field_qa_question',
			'label' => '質問',
			'name' => 'question',
			'type' => 'wysiwyg',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'formatting' => 'html',
			'instructions' => '',
		),
                array(
                    'key' => 'field_qa_answer',
                    'label' => '答え',
                    'name' => 'answer',
                    'type' => 'repeater',
                    'row_min' => '1',
                    'row_limit' => '6',
                    'layout' => 'table',
                    'button_label' => '回答文追加',
                    'instructions' => '',
                    'sub_fields' => array (
                        array(
                            'key' => 'fields_qa_answer_sub_title',
                            'label' => 'タイトル',
                            'name' => 'sub',
                            'type' => 'text',
                            'required' => 0,
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'formatting' => 'br',
                            'instructions' => '',
                        ),
                        array (
							'key' => 'field_qa_body',
							'label' => '本文',
							'name' => 'body',
							'type' => 'wysiwyg',
							'required' => 0,
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'formatting' => 'html',
							'instructions' => '',
						),
                    ),                    
                ),
  //               array (
		// 	'key' => 'field_qa_answer',
		// 	'label' => '',
		// 	'name' => 'label',
		// 	'type' => 'text',
		// 	'required' => 0,
		// 	'default_value' => '',
		// 	'placeholder' => '',
		// 	'maxlength' => '',
		// 	'formatting' => 'html',
		// 	'instructions' => '',
		// ),
                array (
			'key' => 'field_qa_magazine_number',
			'label' => '月刊不動産号数',
			'name' => 'mana',
			'type' => 'text',
			'required' => 0,
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'formatting' => 'html',
			'instructions' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'qa',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'options' => array (
		'position' => 'normal',
		'layout' => 'default',
		'hide_on_screen' => array (
                        //0 => 'the_content',
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'custom_fields',
			4 => 'discussion',
			5 => 'comments',
			6 => 'revisions',
			7 => 'slug',
			8 => 'author',
			9 => 'format',
			10 => 'featured_image',
			11 => 'categories',
			12 => 'tags',
			13 => 'send-trackbacks',
		),
	),
	'menu_order' => 0,
));